### ISSUE TITLE
Stuck on Error : predict_time = int(ARGS.trend_time) 

### ISSUE THREAD

**Issue by antonistet** [declasm/binance_harvester#1]
hello Iam trying to get through the following message but I didnt manage to , because Iam very amateur in coding.  I run in Windows with python 3.9 and all requirements were ok (I had one problem only with Ta_lib but I found my system compatible version here... https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib )

Any help would be much appreciated

line 41, in <module>
    predict_time = int(ARGS.trend_time)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by declasm** [comment]
I added a note about setting up ta-lib in the readme.
Did you start the harvester with the -T 5 (or whatever hourly trend time) parameter?

**Comment by antonistet** [comment]
thank you very much...!
